name: grow_hooks
description: Reusable set of Flutter hooks used across our multiple projects.
version: 0.1.2
repository: https://github.com/Code-Growers/grow_hooks
issue_tracker: https://github.com/Code-Growers/grow_hooks/issues
homepage: https://codegrowers.tech

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  index_generator: 3.4.1

flutter:
  generate: true
