name: grow_hooks
description: Reusable set of Flutter hooks
version: 0.0.1
homepage: https://github.com/Code-Growers/grow_hooks

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.5
  flutter_vibrate: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  index_generator: 3.4.1

flutter:
  generate: true
